server:
  port: 8081
  
spring:
  application:
    name: catalog
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    server-url:
      defaultZone: http://127.0.0.1:8761/eureka
    
# 서버가 많아지면 아래로 쭉 적어서 리스트 만들어주면됨   
# yml 야믈파일은 들여쓰기 = . 으로 인식되므로 꼭 들여쓰기 해주어야 함